### ISSUE TITLE
Circular reference compilation problem with aligned_allocator.h...

### ISSUE THREAD

**Issue by dicroce** [nyanp/tiny-cnn#76]
aligned_allocator.h uses nn_error, which is defined in util.h...

But, util.h includes aligned_allocator.h before it defines nn_error... As a temporary fix, I changed aligned_allocator.h line 68 to throw a std::exception (via std::runtime_error())... But it's not a good fix because we probably want to use nn_error consistently... I'm creating this bug so this is a known issue...

Actually, I am confused how anyone is compiling right now...

**Comment by dan-1d** [comment]
Yes! I just pulled this project and started playing.. sure enough I got the same error. Probably should be addressed in a more formal manner.  This may not happen with some build systems if files are seen in different order, but I'm pretty sure this is a real issue.

My fix was to re-order the include in util.h:

////////////////////
#include <string>
///   this needs to appear before the aligned_allocator include
///               so that nn_error is declared prior
class nn_error : public std::exception {
public:
    explicit nn_error(const std::string& msg) : msg_(msg) {}
    const char* what() const throw() override { return msg_.c_str(); }
private:
    std::string msg_;
};
#include "aligned_allocator.h"

#ifdef CNN_USE_TBB

/////////////

**Comment by dicroce** [comment]
Ok, good! I'm not crazy... :)

**Comment by nyanp** [comment]
Oh I was crazy... I'll fix it!
